var list = new Array(
{ name:"Bluegrass Country", 
  url:"http://ice24.securenetsystems.net/WAMU" },
{ name:"Blues Classics", 
  url:"http://wms-15.streamsrus.com:11610/;stream.nsv", 
  vol:-1000 },
{ name:"Absolute 70s", 
  url:"http://stream.timlradio.co.uk/ABSOLUTE70SIRMP3?ats=1&awparams=loggedin:false", 
  vol:-1000 },
{ name:"Jazz Radio", 
  url:"http://jazzblackmusic.ice.infomaniak.ch/jazzblackmusic-high.mp3", 
  vol:-1000 },
{ name:"Dokumente", 
  url:"http://dradio_mp3_dokdeb_s.akacast.akamaistream.net/7/725/142684/v1/gnl.akacast.akamaistream.net/dradio_mp3_dokdeb_s" },
{ name:"RFI", 
  url:"http://95.81.155.3/rfimonde/all/rfimonde-64k.mp3", 
  vol:-500 },
{ name:"BBC World Service", 
  url:"http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk_backup" },
{ name:"BBC Radio 4 Extra",
  url:"http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_radio_four_extra.m3u8",
  vol:-500 },
{ name:"BBC Radio 4 Long Wave",
  url:"http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_radio_fourlw.m3u8",
  vol:-500 },
{ name:"BBC 5 Live",
  url:"http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_radio_five_live.m3u8",
  vol:-500 },
{ name:"BBC 5 Live Sports Extra",
  url:"http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/ak/bbc_radio_five_live_sports_extra.m3u8",
  vol:-500 }
);


exports.list = list;